---
settings:
  name: Converged Systems Advisor
  rss_page: reference_new.html
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-cn,us-en,ja-jp,ko-kr,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Converged Systems Advisor 文档
    url: "/index.html"
  - title: 发行说明
    entries:
    - title: 新增功能
      url: "/reference_new.html"
    - title: 新增功能归档
      url: "/reference_archive.html"
    - title: 已知问题
      url: "/reference_issues.html"
  - title: 概念
    entries:
    - title: 概述
      url: "/concept_overview.html"
    - title: 架构
      url: "/concept_architecture.html"
    - title: 许可
      url: "/concept_licensing.html"
    - title: 安全性
      url: "/concept_security.html"
    - title: 用户角色
      url: "/reference_user_roles.html"
  - title: 入门
    entries:
    - title: 快速入门
      url: "/task_quick_start.html"
    - title: 准备您的环境
      url: "/task_prepare_environment.html"
    - title: 为 FlexPod 设备创建帐户
      url: "/task_create_accounts_flexpod_devices.html"
    - title: 设置和部署代理
      url: "/task_setup_deploy_agent.html"
    - title: 在门户中添加基础架构
      url: "/task_add_infrastructure.html"
    - title: 配置通知
      url: "/task_configure_notifications.html"
    - title: 在代理上设置静态 IP
      url: "/task_setting_static_ip.html"
  - title: 监控基础架构
    entries:
    - title: 查看基础架构历史记录
      url: "/task_review_infrastructure_history.html"
    - title: 监控规则
      url: "/task_monitor_rules.html"
    - title: 生成报告
      url: "/task_generate_reports.html"
    - title: 跟踪支持合同
      url: "/task_track_contracts.html"
  - title: 验证合作伙伴和经销商的部署
    url: "/task_deployment_validation_partners_resellers.html"
  - title: 故障排除
    url: "/task_troubleshooting.html"
  - title: 相关链接
    url: "/reference_additional_info.html"
  - title: 法律声明
    url: "/reference_legal_notices.html"
